version: "3.8"

services:
  db:
    image: mysql/mysql-server:8.0.19
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=laraib
      - MYSQL_PASSWORD=laraib
      - MYSQL_DATABASE=lost_and_found_docker
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_USER= root
      - PMA_PASSWORD= root
    depends_on:
      - db